# Generated by Django 6.1 on 2026-09-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0006_staff_phone_10_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='admin_backend.department'),
        ),
    ]
