# Generated by Django 6.1 on 2026-09-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medicine_type', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=100, unique=True)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('issued_quantity', models.PositiveIntegerField()),
                ('price_at_issue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacist_backend.issuedprescription')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacist_backend.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=20)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('issued_prescription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='pharmacist_backend.issuedprescription')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('doctor_name', models.CharField(max_length=200)),
                ('is_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacist_backend.pharmacypatient')),
            ],
        ),
        migrations.AddField(
            model_name='issuedprescription',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescription', to='pharmacist_backend.pharmacyprescription'),
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('prescribed_quantity', models.PositiveIntegerField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacist_backend.pharmacyprescription')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('change', models.IntegerField()),
                ('action', models.CharField(choices=[('ADD', 'Stock Added'), ('UPDATE', 'Stock Updated'), ('ISSUE', 'Medicine Issued'), ('DELETE', 'Medicine Deleted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_history', to='pharmacist_backend.medicine')),
            ],
        ),
    ]
