# Generated by Django 6.1 on 2026-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='action',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='transaction_type',
            field=models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out'), ('ADD', 'Stock Added'), ('UPDATE', 'Stock Updated'), ('ISSUE', 'Medicine Issued'), ('DELETE', 'Medicine Deleted')], default='Stock In', max_length=20),
        ),
    ]
