# Generated by Django 6.1 on 2026-09-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_backend', '0002_alter_stockhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedprescription',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='pharmacybill',
            name='issued_prescription',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='medicine_name',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='pharmacist_backend.medicine'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='transaction_type',
            field=models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out')], default='Stock In', max_length=20),
        ),
        migrations.DeleteModel(
            name='IssuedMedicine',
        ),
        migrations.DeleteModel(
            name='IssuedPrescription',
        ),
        migrations.DeleteModel(
            name='PharmacyBill',
        ),
    ]
