# Generated by Django 6.1 on 2026-09-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_backend', '0003_remove_issuedprescription_prescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacypatient',
            old_name='patient_code',
            new_name='patient_id',
        ),
    ]
