# Generated by Django 6.1 on 2026-09-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_backend', '0004_rename_patient_code_pharmacypatient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescription', to='pharmacist_backend.pharmacyprescription')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('issued_quantity', models.PositiveIntegerField()),
                ('price_at_issue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacist_backend.medicine')),
                ('issued_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacist_backend.issuedprescription')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=20)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('issued_prescription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='pharmacist_backend.issuedprescription')),
            ],
        ),
    ]
