# Generated by Django 6.1 on 2026-09-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0007_labtest_department'),
        ('pharmacist_backend', '0005_issuedprescription_issuedmedicine_pharmacybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='master_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_inventory', to='admin_backend.medicine'),
        ),
    ]
