# Generated by Django 6.1 on 2026-09-07 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend', '0002_prescribedlabtest_prescribedmedicine'),
        ('pharmacist_backend', '0006_medicine_master_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedprescription',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_issued_prescription', to='doctor_backend.consultation'),
        ),
        migrations.AlterField(
            model_name='issuedprescription',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescription', to='pharmacist_backend.pharmacyprescription'),
        ),
    ]
