# Generated by Django 6.1.1 on 2026-09-03 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('admin_backend', '0005_alter_labtest_options_alter_medicine_options'),
    ('receptionist_backend', '0001_initial'),
]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='16:00')),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_availabilities', to='admin_backend.doctorprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day_of_week'), name='unique_doctor_availability_per_day')],
            },
        ),
    ]
