# Generated by Django 6.1.1 on 2026-09-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('admin_backend', '0005_alter_labtest_options_alter_medicine_options'),
    ('receptionist_backend', '0002_doctoravailability'),
]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token_number', models.PositiveIntegerField()),
                ('appointment_type', models.CharField(choices=[('PRIOR', 'Prior Appointment'), ('CONSULTATION', 'Consultation')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptionist_appointments', to='admin_backend.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptionist_appointments', to='admin_backend.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='receptionist_backend.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_doctor_appointment_slot'), models.UniqueConstraint(fields=('doctor', 'appointment_date', 'token_number'), name='unique_doctor_daily_token')],
            },
        ),
    ]
