# Generated by Django 6.1.1 on 2026-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0005_alter_labtest_options_alter_medicine_options'),
        ('receptionist_backend', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_daily_token',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SCHEDULED')), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_active_doctor_appointment_slot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SCHEDULED')), fields=('doctor', 'appointment_date', 'token_number'), name='unique_active_doctor_daily_token'),
        ),
    ]
