# Generated by Django 6.1 on 2026-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_backend', '0005_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_CONSULTATION', 'In Consultation'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20),
        ),
    ]
