# Generated by Django 6.1 on 2026-09-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0005_alter_labtest_options_alter_medicine_options'),
        ('doctor_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_lab_tests', to='doctor_backend.consultation')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='admin_backend.labtest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consultation', 'lab_test'), name='unique_lab_test_per_consultation')],
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('instructions', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to='doctor_backend.consultation')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='admin_backend.medicine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consultation', 'medicine'), name='unique_medicine_per_consultation')],
            },
        ),
    ]
