# Generated by Django 6.1 on 2026-09-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0007_labtest_department'),
        ('lab_technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_lab_reports', to='admin_backend.staff')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_report', to='lab_technician.labtestrequest')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_report', to='lab_technician.labresult')),
            ],
        ),
    ]
