# Generated by Django 6.1 on 2026-09-07 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend', '0002_prescribedlabtest_prescribedmedicine'),
        ('lab_technician', '0003_laboratorybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='doctor_prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_test_request', to='doctor_backend.prescribedlabtest'),
        ),
    ]
